### ISSUE TITLE
Relacja jeden-do-wielu bez podawania całego obiektu

### ISSUE THREAD

**Issue by sulmar** [sulmar/Altkom.Bosch.EF#8]
Chciałbym zadać pytanie w kontekście szkolenia z Entity Framework 6, w którym uczestniczyłem z kolegami z Bosch w dniach 11-13 września.
 
Otóż mamy Code First i relację jeden-do-wielu zdefiniowaną poprzez navigation property. Model nie zawiera pól odpowiedzialnych za klucze obce, pola te są tylko w bazie danych.
Czy jest możliwe stworzenie obiektu będącego w relacji jeden-do-wielu w po stronie "wiele" (czyli klucza obcego), mając tylko ID klucza głównego bez podawania (pobranego z bazy) całego obiektu po stronie "jeden"?
 
A jeśli nie jest to możliwe, to jaka jest dobra praktyka związana z tym zagadnieniem (np. dodawanie do modelu pól będącymi kluczami obcymi do których jawnie można przypisywać ID)?

**Comment by sulmar** [comment]
Witam,
Tak istnieje taka możliwość. 

Weźmy na przykład taki model:

~~~ csharp

 public class Department
    {
        public int DepartmentID { get; set; }
        public string Name { get; set; }
        public ICollection<Employee> Employees { get; set; }
    }

 public class Employee
    {
        public int EmployeeID { get; set; }
        public string Name { get; set; }

        public int? DepartmentId { get; set; }
        public Department Department { get; set; }
    }


~~~

Dodałem w nim pole DepartmentId, które będzie skojarzone z polem Department za pomocą następującej konfiguracji:

~~~ csharp
  modelBuilder.Entity<Employee>()
               .HasOptional(e => e.Department)
               .WithMany(d => d.Employees)
               .HasForeignKey(e => e.DepartmentId);
~~~ 

Dzięki temu może dodać teraz pracownika wraz z określonym działem bez potrzeby pobierania obiektu departamentu:

~~~ csharp

 var employee = new Employee { Name = "Marcin", DepartmentId = 2 };

            using (var context = new MyContext())
            {
                var employees = context.Employees.Add(employee);

                context.SaveChanges();
            }

~~~

Warto zauważyć, że możemy również filtrować pracowników po takim polu bez potrzeby pobierania działów:

~~~ csharp
var departmentId = 2;

            using (var context = new MyContext())
            {
                var employees = context.Employees
                    .Where(e=>e.DepartmentId == departmentId)
                    .ToList();
            }

~~~

Jeśli chodzi o praktykę to najczęściej pracuję na całych obiektach, ale w sytuacjach gdy pobieramy całe obiekty tylko po aby je podpiąć pod zapisywany obiekt to rzeczywiście warto zastosować powyższe rozwiązanie. Dzięki niemu zyskamy na wydajności.

**Comment by mtomekm** [comment]
Dziękuję Panie Marcinie za rozwiązanie. Ten sposób rozwiązuje nasz problem.
